---
env:
  contexts:
  - name: ""
    urls:
    - ""
    includePaths:
    - ""
    excludePaths: []
    authentication:
      method: ""
      parameters:
        loginPageUrl: ""
        loginRequestUrl: ""
        loginRequestBody: ""
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: ""
      parameters: {}
    technology:
      exclude: []
    users:
    - name: ""
      credentials:
        password: ""
        username: ""
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
    disableAllRules: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters:
    context: ""
    user: ""
    url: ""
    maxDuration: 0
    maxDepth: 0
    maxChildren: 0
  name: "spider"
  type: "spider"
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters:
    context: ""
    user: ""
    url: ""
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 8
    inScopeOnly: true
    runOnlyIfModern: false
  name: "spiderAjax"
  type: "spiderAjax"
  tests:
  - onFail: "INFO"
    statistic: "spiderAjax.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"