# Use a imagem oficial do Python como base
FROM python:3.12.5-slim

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia o arquivo requirements.txt para o contêiner
COPY requirements.txt .

# Instala as dependências Python
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do código da aplicação para o contêiner
COPY . .

# Configura a variável de ambiente do Flask
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=8000

# Define o diretório de upload para a aplicação Flask (apontando para o volume compartilhado)
ENV UPLOAD_FOLDER=/shared_data

# Expõe a porta 8000 para acesso externo
EXPOSE 8000

# Comando para iniciar a aplicação Flask
CMD ["flask", "run"]
